export const modelData = {
  tables: [
    {
      code: null,
      comment: 'desc!!',
      count: null,
      createBy: null,
      createByName: null,
      createTime: null,
      databaseId: '1aa',
      dbInstanceId: 1,
      dbType: 'mysql',
      id: 'adfgsdgfsdfgsgfsdfgxddf',
      indexNames: null,
      instanceId: null,
      isParent: false,
      loading: false,
      modelNum: '1',
      name: 'testtable2【测试表格2】',
      order: 1,
      parentId: '1aa',
      partirionKeys: null,
      physicalName: '测试表格2',
      primaryKeys: null,
      realId: null,
      realParentId: null,
      schema: null,
      systemId: null,
      type: 'table',
      updateTime: 1606159424000,
      columns: [
        {
          id: '1',
          modelTableId: '1aa',
          columnName: 'tb1col1',
          columnDesc: 'd3',
          columnType: '0',
          comment: 'd',
          isPk: 1,
          isFk: 1,
          isNull: 1,
          isAutoIncre: 1,
          defaultValue: '777',
          order: 1,
          isView: null
        },
        {
          id: '2',
          modelTableId: '1aa',
          columnName: 'tb1col2',
          columnDesc: 'd2',
          columnType: '0',
          comment: 'd2',
          isPk: 0,
          isFk: 1,
          isNull: 0,
          isAutoIncre: 0,
          defaultValue: '0',
          order: 1,
          isView: null
        },
        {
          id: '3',
          modelTableId: '1aa',
          columnName: 'tb1col3',
          columnDesc: 'd2',
          columnType: '0',
          comment: 'd2',
          isPk: 0,
          isFk: 0,
          isNull: 0,
          isAutoIncre: 0,
          defaultValue: '0',
          order: 1,
          isView: null
        }
      ],
      x: 100,
      y: 100
    },
    {
      code: null,
      comment: 'desc!!',
      count: null,
      createBy: null,
      createByName: null,
      createTime: null,
      databaseId: '1aa',
      dbInstanceId: 1,
      dbType: 'mysql',
      id: 'asdfasfasdfasdfas',
      indexNames: null,
      instanceId: null,
      isParent: false,
      loading: false,
      modelNum: '1',
      name: 'tesbiaot【测试表格1】',
      order: 1,
      parentId: '1aa',
      partirionKeys: null,
      physicalName: '测试表格1',
      primaryKeys: null,
      realId: null,
      realParentId: null,
      schema: null,
      systemId: null,
      type: 'table',
      updateTime: 1606159418000,
      columns: [
        {
          id: '3',
          modelTableId: '2bb',
          columnName: 'tb2col1',
          columnDesc: 'd2',
          columnType: '0',
          comment: 'd2',
          isPk: 0,
          isFk: 0,
          isNull: 0,
          isAutoIncre: 0,
          defaultValue: '0',
          order: 1,
          isView: null
        }
      ],
      x: 600,
      y: 100
    }
  ],
  relations: [
    // {
    //   id: 1,
    //   fromTableId: 'adfgsdgfsdfgsgfsdfgxddf',
    //   fromTableColumnId: 'tb1col1',
    //   toTableId: 'asdfasfasdfasdfas',
    //   toTableColumnId: 'tb2col1',
    //   dbInstanceId: 1,
    //   fromAnchor: 1,
    //   toAnchor: 0,
    //   fromArrow: '0,n',
    //   toArrow: '1',
    //   controlPoints: [{
    //     x: 450, y: 100
    //   }]
    // }
    // {
    //   id: 2,
    //   fromTableId: '1aa',
    //   fromTableColumnId: 'tb1col2',
    //   toTableId: '2bb',
    //   toTableColumnId: 'tb2col1',
    //   dbInstanceId: 1,
    //   fromAnchor: 3,
    //   toAnchor: 0,
    //   fromArrow: '0,n',
    //   toArrow: '1',
    //   controlPoints: [{
    //     x: 300, y: 300
    //   }]
    // }
  ]
}

export const addItem = {
  code: null,
  comment: 'desc!!',
  count: null,
  createBy: null,
  createByName: null,
  createTime: null,
  databaseId: '1aa',
  dbInstanceId: 1,
  dbType: 'mysql',
  indexNames: null,
  instanceId: null,
  isParent: false,
  loading: false,
  modelNum: '1',
  name: 'testtable2【测试表格2】',
  order: 1,
  parentId: '1aa',
  partirionKeys: null,
  physicalName: '测试表格2',
  primaryKeys: null,
  realId: null,
  realParentId: null,
  schema: null,
  systemId: null,
  type: 'table',
  updateTime: 1606159424000,
  columns: [
    {
      id: '3',
      modelTableId: '2bb',
      columnName: 'tb2col1',
      columnDesc: 'd2',
      columnType: '0',
      comment: 'd2',
      isPk: 0,
      isFk: 0,
      isNull: 0,
      isAutoIncre: 0,
      defaultValue: '0',
      order: 1,
      isView: null
    }
  ]
}
